version: "3.8"
services:
  postgres:
    image: postgres:15.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 15432:5432
    networks:
      - w2p
volumes:
  postgres-data:
networks:
  w2p:
